# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CD
on:
  push:
    branches: [ "feature/1-ci-cd", "main" ]
  pull_request:
    branches: [ "feature/1-ci-cd", "main" ]

jobs:
  build:
    name: Building and Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "razor-app-2022" #Must be unique in Heroku
          heroku_email: "supun.edirisuriya@the-ai.team"