name: onPR
on:
  pull_request:
    branches: '**'

jobs:
  build:
    name: Building and Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build 
      - run: npm run test
      - run: npm run make-badges:ci
      - run: npm run coverage:codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          flags: coverage